# Generated by Django 5.1.3 on 2024-12-01 19:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistModel',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=200)),
                ('genres', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.TextField(blank=True)),
                ('album_name', models.TextField(blank=True)),
                ('album_image', models.TextField(blank=True)),
                ('track_name', models.TextField(blank=True)),
                ('artist_list', models.JSONField(default=list)),
                ('preview_url', models.TextField(blank=True, null=True)),
                ('popularity_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.TextField(default=0, primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='', max_length=30)),
                ('pfp', models.TextField(blank=True, default='', null=True)),
                ('product', models.TextField(default='')),
                ('uri', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='WrapModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('top_audio', models.TextField(blank=True)),
                ('personality', models.JSONField(default=list)),
                ('color', models.TextField(blank=True)),
                ('top_genres', models.JSONField(blank=True, default=dict)),
                ('suggested_tracks', models.ManyToManyField(related_name='suggested_tracks', to='spotify_wrapped.trackmodel')),
                ('top_artists', models.ManyToManyField(to='spotify_wrapped.artistmodel')),
                ('top_tracks', models.ManyToManyField(related_name='top_tracks', to='spotify_wrapped.trackmodel')),
                ('user', models.ManyToManyField(related_name='user', to='spotify_wrapped.usermodel')),
            ],
        ),
    ]
