# Generated by Django 5.1.2 on 2024-10-30 06:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=0, max_length=22, primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wrap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('users', models.ManyToManyField(to='spotify_wrapped.user')),
            ],
        ),
    ]
