# Generated by Django 5.1.3 on 2024-11-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_wrapped', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackmodel',
            name='popularity_score',
            field=models.IntegerField(default=0),
        ),
    ]
