# Generated by Django 5.1.2 on 2024-10-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_wrapped', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_id',
            field=models.CharField(default=0, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
