# Generated by Django 5.1.3 on 2024-11-14 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_wrapped', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='wrap',
            name='users',
        ),
        migrations.AddField(
            model_name='wrap',
            name='color',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wrap',
            name='personality',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='wrap',
            name='top_audio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wrap',
            name='top_genres',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wrap',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotify_wrapped.user'),
        ),
        migrations.AddField(
            model_name='wrap',
            name='top_artists',
            field=models.ManyToManyField(to='spotify_wrapped.artist'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.TextField(blank=True)),
                ('album_image', models.TextField(blank=True)),
                ('track_name', models.TextField(blank=True)),
                ('artist_list', models.ManyToManyField(related_name='artist_list', to='spotify_wrapped.artist')),
            ],
        ),
        migrations.AddField(
            model_name='wrap',
            name='suggested_tracks',
            field=models.ManyToManyField(related_name='suggested_tracks', to='spotify_wrapped.track'),
        ),
        migrations.AddField(
            model_name='wrap',
            name='top_tracks',
            field=models.ManyToManyField(related_name='top_tracks', to='spotify_wrapped.track'),
        ),
    ]
