# Generated by Django 5.1.3 on 2024-11-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_wrapped', '0002_artist_remove_wrap_users_wrap_color_wrap_personality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='product',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='uri',
            field=models.TextField(default=''),
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist_list',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.TextField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='track',
            name='artist_list',
            field=models.JSONField(default=list),
        ),
    ]
