# Generated by Django 5.1.3 on 2024-11-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_wrapped', '0002_trackmodel_popularity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistmodel',
            name='genres',
            field=models.JSONField(default=list),
        ),
    ]
