# Generated by Django 5.1.3 on 2024-11-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_wrapped', '0003_user_pfp_user_product_user_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.TextField(blank=True, default=''),
        ),
    ]
