# Generated by Django 5.1.3 on 2024-11-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_wrapped', '0004_alter_artistmodel_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistmodel',
            name='genres',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
