# Generated by Django 5.1.3 on 2024-11-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_wrapped', '0005_alter_user_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrap',
            name='user',
        ),
        migrations.AddField(
            model_name='wrap',
            name='user',
            field=models.ManyToManyField(related_name='user', to='spotify_wrapped.user'),
        ),
    ]
