# Generated by Django 5.1.3 on 2024-11-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_wrapped', '0006_remove_wrap_user_wrap_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='preview_url',
            field=models.TextField(blank=True),
        ),
    ]
