# Generated by Django 5.1.3 on 2024-11-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_wrapped', '0007_track_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='preview_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
