# Generated by Django 5.1.3 on 2024-11-23 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_wrapped', '0008_alter_track_preview_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='ArtistModel',
        ),
        migrations.RenameModel(
            old_name='Track',
            new_name='TrackModel',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
        migrations.RenameModel(
            old_name='Wrap',
            new_name='WrapModel',
        ),
    ]
