# Generated by Django 5.1.3 on 2024-11-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_wrapped', '0009_rename_artist_artistmodel_rename_track_trackmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackmodel',
            name='track_id',
            field=models.TextField(blank=True),
        ),
    ]
